/*global systemDictionary:true */
"use strict";

systemDictionary = {
	"AlarmControl adapter settings": {
		"en": "Adapter settings for AlarmControl",
		"de": "Adaptereinstellungen für AlarmControl",
		"ru": "Настройки адаптера для AlarmControl",
		"pt": "Configurações do adaptador para AlarmControl",
		"nl": "Adapterinstellingen voor AlarmControl",
		"fr": "Paramètres d'adaptateur pour AlarmControl",
		"it": "Impostazioni dell'adattatore per AlarmControl",
		"es": "Ajustes del adaptador para AlarmControl",
		"pl": "Ustawienia adaptera dla AlarmControl",
		"zh-cn": "AlarmControl的适配器设置"
	},
	"Notification settings": {
    "en": "Notification settings",
    "de": "Benachrichtigungseinstellungen",
    "ru": "Настройки уведомлений",
    "pt": "Configurações de notificação",
    "nl": "Notificatie instellingen",
    "fr": "Paramètres de notification",
    "it": "Impostazioni di notifica",
    "es": "Configuración de las notificaciones",
    "pl": "Ustawienia powiadomień",
    "zh-cn": "通知设置"
  },
    "Cancel": {
    "en": "Cancel",
    "de": "Abbrechen",
    "ru": "Отмена",
    "pt": "Cancelar",
    "nl": "Annuleer",
    "fr": "Annuler",
    "it": "Annulla",
    "es": "Cancelar",
    "pl": "Anuluj",
    "zh-cn": "取消"
  },
   "Select": {
    "en": "Select",
    "de": "Wählen",
    "ru": "Выбрать",
    "pt": "Selecione",
    "nl": "Selecteer",
    "fr": "Sélectionner",
    "it": "Selezionare",
    "es": "Seleccione",
    "pl": "Wybierz",
    "zh-cn": "选择"
  },
   "Warning phrase: If the set opening time is exceeded (Entrance).": {
    "en": "Warning phrase: If the set opening time is exceeded (Entrance).",
    "de": "Warnhinweis: Wenn die eingestellte Öffnungszeit überschritten wird (Eingang).",
    "ru": "Предупреждающая фраза: Если установленное время открытия превышено (Вход).",
    "pt": "Frase de advertência: Se o tempo de abertura definido for ultrapassado (Entrada).",
    "nl": "Waarschuwingszin: als de ingestelde openingstijd wordt overschreden (ingang).",
    "fr": "Phrase d'avertissement: Si le temps d'ouverture réglé est dépassé (Entrée).",
    "it": "Frase di avvertimento: se viene superato il tempo di apertura impostato (Ingresso).",
    "es": "Frase de advertencia: Si se excede el tiempo de apertura establecido (Entrada).",
    "pl": "Fraza ostrzegawcza: Przekroczenie ustawionego czasu otwarcia (Wejście).",
    "zh-cn": "警告词：如果超过设定的开放时间（入口）。"
  },
   "Alarm activation time (no one present)": {
    "en": "Alarm activation time (no one present)",
    "de": "Alarmaktivierungszeit (niemand anwesend)",
    "ru": "Время срабатывания будильника (никого нет)",
    "pt": "Tempo de ativação do alarme (ninguém presente)",
    "nl": "Alarm activeringstijd (niemand aanwezig)",
    "fr": "Heure d'activation de l'alarme (personne n'est présent)",
    "it": "Tempo di attivazione dell'allarme (nessuno presente)",
    "es": "Hora de activación de la alarma (no hay nadie presente)",
    "pl": "Czas aktywacji alarmu (nikt nie jest obecny)",
    "zh-cn": "警报激活时间（无人）"
  },
    "Report alarm changes": {
    "en": "Report alarm changes",
    "de": "Alarmänderungen melden",
    "ru": "Сообщать об изменениях сигналов тревоги",
    "pt": "Reportar alterações de alarme",
    "nl": "Meld alarmwijzigingen",
    "fr": "Signaler les changements d'alarme",
    "it": "Segnala le modifiche agli allarmi",
    "es": "Informar cambios de alarma",
    "pl": "Zgłoś zmiany w alarmach",
    "zh-cn": "报告警报更改"
  },
    "Voice notification": {
    "en": "Voice notification",
    "de": "Sprachbenachrichtigung",
    "ru": "Голосовое уведомление",
    "pt": "Notificação de voz",
    "nl": "Spraakmelding",
    "fr": "Notification vocale",
    "it": "Notifica vocale",
    "es": "Notificación de voz",
    "pl": "Powiadomienie głosowe",
    "zh-cn": "语音通知"
  },
   "Warning phrase: when motion is detected": {
    "en": "Warning phrase: when motion is detected",
    "de": "Warnhinweis: Wenn eine Bewegung erkannt wird",
    "ru": "Предупреждающая фраза: при обнаружении движения",
    "pt": "Frase de advertência: quando o movimento é detectado",
    "nl": "Waarschuwingszin: wanneer beweging wordt gedetecteerd",
    "fr": "Phrase d'avertissement: lorsqu'un mouvement est détecté",
    "it": "Frase di avviso: quando viene rilevato un movimento",
    "es": "Frase de advertencia: cuando se detecta movimiento",
    "pl": "Fraza ostrzegawcza: po wykryciu ruchu",
    "zh-cn": "警告词：检测到运动时"
  },
  "Voice command to turn off the alarm (Level 2)": {
    "en": "Voice command to turn off the alarm (Level 2)",
    "de": "Sprachbefehl zum Ausschalten des Alarms (Stufe 2)",
    "ru": "Голосовая команда для выключения будильника (Уровень 2)",
    "pt": "Comando de voz para desligar o alarme (Nível 2)",
    "nl": "Spraakopdracht om het alarm uit te schakelen (niveau 2)",
    "fr": "Commande vocale pour désactiver l'alarme (niveau 2)",
    "it": "Comando vocale per disattivare l'allarme (Livello 2)",
    "es": "Comando de voz para apagar la alarma (Nivel 2)",
    "pl": "Polecenie głosowe wyłączające alarm (poziom 2)",
    "zh-cn": "语音命令可关闭警报（级别2）"
  },
   "Voice command to change the alarm level (without number)": {
    "en": "Voice command to change the alarm level (without number)",
    "de": "Sprachbefehl zum Ändern der Alarmstufe (ohne Nummer)",
    "ru": "Голосовая команда для изменения уровня тревоги (без номера)",
    "pt": "Comando de voz para alterar o nível de alarme (sem número)",
    "nl": "Spraakopdracht om het alarmniveau te wijzigen (zonder nummer)",
    "fr": "Commande vocale pour changer le niveau d'alarme (sans numéro)",
    "it": "Comando vocale per modificare il livello di allarme (senza numero)",
    "es": "Comando de voz para cambiar el nivel de alarma (sin número)",
    "pl": "Polecenie głosowe, aby zmienić poziom alarmu (bez numeru)",
    "zh-cn": "语音命令更改警报级别（无数字）"
  },
   "Alarm": {
    "en": "Alarm",
    "de": "Alarm",
    "ru": "Тревога",
    "pt": "Alarme",
    "nl": "Alarm",
    "fr": "Alarme",
    "it": "Allarme",
    "es": "Alarma",
    "pl": "Alarm",
    "zh-cn": "报警"
  },
   "Family member": {
    "en": "Family member",
    "de": "Familienmitglied",
    "ru": "Член семьи",
    "pt": "Membro da família",
    "nl": "Familielid",
    "fr": "Membre de la famille",
    "it": "Membro della famiglia",
    "es": "Miembro de la familia",
    "pl": "Członek rodziny",
    "zh-cn": "家庭成员"
  },
    "Active": {
    "en": "Active",
    "de": "Aktiv",
    "ru": "активный",
    "pt": "Ativo",
    "nl": "Actief",
    "fr": "actif",
    "it": "Attivo",
    "es": "Activo",
    "pl": "Aktywny",
    "zh-cn": "活性"
  },
    "Family member": {
    "en": "Family member",
    "de": "Familienmitglied",
    "ru": "Член семьи",
    "pt": "Membro da família",
    "nl": "Familielid",
    "fr": "Membre de la famille",
    "it": "Membro della famiglia",
    "es": "Miembro de la familia",
    "pl": "Członek rodziny",
    "zh-cn": "家庭成员"
  },
   "Presence Object": {
    "en": "Presence Object",
    "de": "Präsenzobjekt",
    "ru": "Объект присутствия",
    "pt": "Objeto Presença",
    "nl": "Aanwezigheidsobject",
    "fr": "Objet de présence",
    "it": "Oggetto di presenza",
    "es": "Objeto de presencia",
    "pl": "Obiekt obecności",
    "zh-cn": "存在对象"
  },
    "Time until absent": {
    "en": "Time until absent",
    "de": "Zeit bis zur Abwesenheit",
    "ru": "Время пока отсутствует",
    "pt": "Tempo até ausente",
    "nl": "Tijd tot afwezig",
    "fr": "Temps jusqu'à l'absence",
    "it": "Tempo fino all'assenza",
    "es": "Tiempo hasta ausente",
    "pl": "Czas do nieobecności",
    "zh-cn": "直到缺席的时间"
  },
    "Delete": {
    "en": "Delete",
    "de": "Löschen",
    "ru": "Удалить",
    "pt": "Excluir",
    "nl": "Verwijderen",
    "fr": "Supprimer",
    "it": "Elimina",
    "es": "Eliminar",
    "pl": "Usunąć",
    "zh-cn": "删除"
  },
   "Edit Delete": {
    "en": "Edit Delete",
    "de": "Bearbeiten Löschen",
    "ru": "Редактировать Удалить",
    "pt": "Editar apagar",
    "nl": "Bewerken verwijderen",
    "fr": "Modifier Supprimer",
    "it": "Modifica Elimina",
    "es": "Editar Borrar",
    "pl": "Edytuj Usuń",
    "zh-cn": "编辑删除"
  },
   "Alarm object": {
    "en": "Alarm object",
    "de": "Alarmobjekt",
    "ru": "Объект тревоги",
    "pt": "Objeto de alarme",
    "nl": "Alarmobject",
    "fr": "Objet d'alarme",
    "it": "Oggetto di allarme",
    "es": "Objeto de alarma",
    "pl": "Obiekt alarmowy",
    "zh-cn": "报警对象"
  },
  "Name": {
    "en": "Name",
    "de": "Name",
    "ru": "название",
    "pt": "Nome",
    "nl": "Naam",
    "fr": "Nom",
    "it": "Nome",
    "es": "Nombre",
    "pl": "Imię",
    "zh-cn": "名称"
  },
	"Edit": {
    "en": "Edit",
    "de": "Bearbeiten",
    "ru": "редактировать",
    "pt": "Editar",
    "nl": "Bewerk",
    "fr": "Éditer",
    "it": "modificare",
    "es": "Editar",
    "pl": "Edytować",
    "zh-cn": "编辑"
  },
    "Add Family member": {
    "en": "Add Family member",
    "de": "Familienmitglied hinzufügen",
    "ru": "Добавить члена семьи",
    "pt": "Adicionar membro da família",
    "nl": "Voeg gezinslid toe",
    "fr": "Ajouter un membre de la famille",
    "it": "Aggiungi un membro della famiglia",
    "es": "Agregar miembro de la familia",
    "pl": "Dodaj członka rodziny",
    "zh-cn": "添加家庭成员"
  },
   "Spoken object": {
    "en": "Spoken object",
    "de": "Sprechobjekt",
    "ru": "Разговорный объект",
    "pt": "Objeto falado",
    "nl": "Gesproken object",
    "fr": "Objet parlé",
    "it": "Oggetto parlato",
    "es": "Objeto hablado",
    "pl": "Przedmiot mówiony",
    "zh-cn": "口语对象"
  },
  "Telegram object": {
    "en": "Telegram object",
    "de": "Telegramobjekt",
    "ru": "Объект Telegram",
    "pt": "Objeto de Telegram",
    "nl": "Telegram-object",
    "fr": "Objet Telegram",
    "it": "Oggetto Telegram",
    "es": "Objeto de Telegram",
    "pl": "Obiekt telegramu",
    "zh-cn": "电报对象"
  },
    "Welcome phrase": {
    "en": "Welcome phrase",
    "de": "Begrüßungssatz",
    "ru": "Приветственная фраза",
    "pt": "Frase de boas-vindas",
    "nl": "Welkom zin",
    "fr": "Phrase de bienvenue",
    "it": "Frase di benvenuto",
    "es": "Frase de bienvenida",
    "pl": "Powitanie",
    "zh-cn": "欢迎词"
  },
   "Warning phrase": {
    "en": "Warning phrase",
    "de": "Warnsatz",
    "ru": "Предупреждающая фраза",
    "pt": "Frase de advertência",
    "nl": "Waarschuwende zin",
    "fr": "Phrase d'avertissement",
    "it": "Frase di avvertimento",
    "es": "Frase de advertencia",
    "pl": "Fraza ostrzegawcza",
    "zh-cn": "警告词"
  },
    "Motion sensor": {
    "en": "Motion sensor",
    "de": "Bewegungssensor",
    "ru": "Датчик движения",
    "pt": "Sensor de movimento",
    "nl": "Bewegingssensor",
    "fr": "Capteur de mouvement",
    "it": "Sensore di movimento",
    "es": "Sensor de movimiento",
    "pl": "Czujnik ruchu",
    "zh-cn": "运动传感器"
  },
    "Motion sensors": {
    "en": "Motion sensors",
    "de": "Bewegungssensoren",
    "ru": "Датчики движения",
    "pt": "Sensores de movimento",
    "nl": "Bewegingssensoren",
    "fr": "Détecteurs de mouvement",
    "it": "Sensori di movimento",
    "es": "Sensores de movimiento",
    "pl": "Czujniki ruchu",
    "zh-cn": "运动传感器"
  },
	"Door and Window sensor": {
    "en": "Door and Window sensor",
    "de": "Tür- und Fenstersensor",
    "ru": "Датчик двери и окна",
    "pt": "Sensor de porta e janela",
    "nl": "Deur- en raamsensor",
    "fr": "Capteur de porte et fenêtre",
    "it": "Sensore per porte e finestre",
    "es": "Sensor de puerta y ventana",
    "pl": "Czujnik drzwi i okien",
    "zh-cn": "门窗传感器"
  },
   "Door and Window sensor object": {
    "en": "Door and Window sensor object",
    "de": "Tür- und Fenstersensorobjekt",
    "ru": "Объект датчика двери и окна",
    "pt": "Objeto sensor de porta e janela",
    "nl": "Deur- en raamsensorobject",
    "fr": "Objet capteur porte et fenêtre",
    "it": "Oggetto sensore porta e finestra",
    "es": "Objeto sensor de puerta y ventana",
    "pl": "Obiekt czujnika drzwi i okna",
    "zh-cn": "门窗传感器对象"
  },
  "Sensor value": {
    "en": "Sensor value",
    "de": "Sensorwert",
    "ru": "Значение датчика",
    "pt": "Valor do Sensor",
    "nl": "Sensorwaarde",
    "fr": "Valeur du capteur",
    "it": "Valore del sensore",
    "es": "Valor del sensor",
    "pl": "Wartość czujnika",
    "zh-cn": "传感器值"
  },
    "object ***Sensor": {
    "en": "object ***Sensor",
    "de": "Objekt *** Sensor",
    "ru": "объект *** Датчик",
    "pt": "objeto *** Sensor",
    "nl": "object *** Sensor",
    "fr": "objet *** Capteur",
    "it": "oggetto *** Sensore",
    "es": "objeto *** Sensor",
    "pl": "obiekt *** Czujnik",
    "zh-cn": "对象***传感器"
  },
	"Door and Window sensors": {
    "en": "Door and Window sensors",
    "de": "Tür- und Fenstersensoren",
    "ru": "Датчики дверей и окон",
    "pt": "Sensores de porta e janela",
    "nl": "Deur- en raamsensoren",
    "fr": "Capteurs de portes et fenêtres",
    "it": "Sensori per porte e finestre",
    "es": "Sensores de puertas y ventanas",
    "pl": "Czujniki drzwi i okien",
    "zh-cn": "门窗传感器"
  },
    "Temperature sensor": {
    "en": "Temperature sensor",
    "de": "Temperatursensor",
    "ru": "Датчик температуры",
    "pt": "Sensor de temperatura",
    "nl": "Temperatuursensor",
    "fr": "Capteur de température",
    "it": "Termometro",
    "es": "Sensor de temperatura",
    "pl": "Czujnik temperatury",
    "zh-cn": "温度感应器"
  },
   "Temperature sensors": {
    "en": "Temperature sensors",
    "de": "Temperatursensoren",
    "ru": "Датчики температуры",
    "pt": "Sensores de temperatura",
    "nl": "Temperatuursensoren",
    "fr": "Capteurs de température",
    "it": "Sensori di temperatura",
    "es": "Sensores de temperatura",
    "pl": "Czujniki temperatury",
    "zh-cn": "温度传感器"
  },
    "Other sensor": {
    "en": "Other sensor",
    "de": "Anderer Sensor",
    "ru": "Другой датчик",
    "pt": "Outro sensor",
    "nl": "Andere sensor",
    "fr": "Autre capteur",
    "it": "Altro sensore",
    "es": "Otro sensor",
    "pl": "Inny czujnik",
    "zh-cn": "其他传感器"
  },
   "Timer": {
    "en": "Timer",
    "de": "Zeitschaltuhr",
    "ru": "Таймер",
    "pt": "Cronômetro",
    "nl": "Timer",
    "fr": "Minuteur",
    "it": "Timer",
    "es": "Temporizador",
    "pl": "Regulator czasowy",
    "zh-cn": "计时器"
  },
	"And Mode": {
    "en": "And Mode",
    "de": "Und Modus",
    "ru": "И режим",
    "pt": "E Modo",
    "nl": "En modus",
    "fr": "Et mode",
    "it": "E la modalità",
    "es": "Y modo",
    "pl": "I tryb",
    "zh-cn": "和模式"
  },
  "Or Mode": {
    "en": "Or Mode",
    "de": "Oder Modus",
    "ru": "Или режим",
    "pt": "Ou modo",
    "nl": "Of modus",
    "fr": "Ou Mode",
    "it": "O Mode",
    "es": "O modo",
    "pl": "Lub tryb",
    "zh-cn": "或模式"
  },
	"Countdown": {
    "en": "Countdown",
    "de": "Countdown",
    "ru": "обратный отсчет",
    "pt": "Contagem regressiva",
    "nl": "Aftellen",
    "fr": "Compte à rebours",
    "it": "Conto alla rovescia",
    "es": "cuenta regresiva",
    "pl": "Odliczanie",
    "zh-cn": "倒数"
  },
   "Other sensors": {
    "en": "Other sensors",
    "de": "Andere Sensoren",
    "ru": "Другие датчики",
    "pt": "Outros sensores",
    "nl": "Andere sensoren",
    "fr": "Autres capteurs",
    "it": "Altri sensori",
    "es": "Otros sensores",
    "pl": "Inne czujniki",
    "zh-cn": "其他传感器"
  },
    "Device": {
    "en": "Device",
    "de": "Gerät",
    "ru": "устройство",
    "pt": "Dispositivo",
    "nl": "Apparaat",
    "fr": "Dispositif",
    "it": "Dispositivo",
    "es": "Dispositivo",
    "pl": "Urządzenie",
    "zh-cn": "设备"
  },
   "Devices": {
    "en": "Devices",
    "de": "Geräte",
    "ru": "приборы",
    "pt": "Dispositivos",
    "nl": "Apparaten",
    "fr": "Dispositifs",
    "it": "dispositivi",
    "es": "Dispositivos",
    "pl": "Urządzenia",
    "zh-cn": "设备"
  },
    "Name your Device": {
    "en": "Name your Device",
    "de": "Benennen Sie Ihr Gerät",
    "ru": "Назовите свое устройство",
    "pt": "Nomeie seu dispositivo",
    "nl": "Geef uw apparaat een naam",
    "fr": "Nommez votre appareil",
    "it": "Assegna un nome al dispositivo",
    "es": "Nombra tu dispositivo",
    "pl": "Nazwij swoje urządzenie",
    "zh-cn": "命名您的设备"
  },
	"object ***on": {
    "en": "object ***on",
    "de": "Objekt *** ein",
    "ru": "объект *** вкл",
    "pt": "objeto *** ligado",
    "nl": "object *** aant",
    "fr": "objet *** marche",
    "it": "oggetto *** on",
    "es": "objeto *** encendido",
    "pl": "obiekt *** wł.",
    "zh-cn": "对象***开/关"
  },
  	"object ***off": {
    "en": "object ***off",
    "de": "Objekt *** aus",
    "ru": "объект *** ввыкл",
    "pt": "objeto *** desligado",
    "nl": "object *** uit",
    "fr": "objet *** arrêt",
    "it": "oggetto *** off",
    "es": "objeto *** apagado",
    "pl": "obiekt *** wył",
    "zh-cn": "对象***开/关"
  },
    "On object": {
    "en": "On object",
    "de": "Ein-Objekt",
    "ru": "Вкл объект",
    "pt": "Objeto ligado",
    "nl": "Aan-object",
    "fr": "Objet On",
    "it": "Oggetto On",
    "es": "Objeto encendido",
    "pl": "Obiekt On",
    "zh-cn": "开/关对象"
  },
   "On Value": {
    "en": "On Value",
    "de": "Ein Wert",
    "ru": "По стоимости",
    "pt": "No valor",
    "nl": "Op waarde",
    "fr": "Sur la valeur",
    "it": "Sul valore",
    "es": "En valor",
    "pl": "Wartość",
    "zh-cn": "价值"
  },
    "Off object": {
    "en": "OOff object",
    "de": "Aus-Objekt",
    "ru": "ВВыкл объект",
    "pt": "Objeto desligado",
    "nl": "uit-object",
    "fr": "Objet Off",
    "it": "Oggetto Off",
    "es": "Objeto apagado",
    "pl": "Obiekt Off",
    "zh-cn": "开/关对象"
  },
    "Off Value": {
    "en": "Off Value",
    "de": "Aus Wert",
    "ru": "Выкл. Значение",
    "pt": "Valor Off",
    "nl": "Uit waarde",
    "fr": "Valeur Off",
    "it": "Off Value",
    "es": "Valor de descuento",
    "pl": "Wartość wyłączenia",
    "zh-cn": "折价"
  },
   "Call name": {
    "en": "Call name",
    "de": "Spitzname",
    "ru": "Назовите имя",
    "pt": "Nome da chamada",
    "nl": "Roep naam",
    "fr": "Nom d'appel",
    "it": "Chiama nome",
    "es": "Nombre de llamada",
    "pl": "Imię i nazwisko",
    "zh-cn": "通话名称"
  },
   "string": {
    "en": "string",
    "de": "Zeichenfolge",
    "ru": "строка",
    "pt": "corda",
    "nl": "draad",
    "fr": "chaîne",
    "it": "corda",
    "es": "cuerda",
    "pl": "strunowy",
    "zh-cn": "串"
  },
    "Value": {
    "en": "Value",
    "de": "Wert",
    "ru": "Стоимость",
    "pt": "Valor",
    "nl": "Waarde",
    "fr": "Valeur",
    "it": "Valore",
    "es": "Valor",
    "pl": "Wartość",
    "zh-cn": "值"
  },
    "Trigger": {
    "en": "Trigger",
    "de": "Auslöser",
    "ru": "Курок",
    "pt": "Desencadear",
    "nl": "Trekker",
    "fr": "Déclencheur",
    "it": "grilletto",
    "es": "Desencadenar",
    "pl": "Wyzwalacz",
    "zh-cn": "触发"
  },
   "Schedule": {
    "en": "Schedule",
    "de": "Zeitplan",
    "ru": "График",
    "pt": "Cronograma",
    "nl": "Schema",
    "fr": "Programme",
    "it": "Programma",
    "es": "Calendario",
    "pl": "Harmonogram",
    "zh-cn": "时间表"
  },
  "Speach": {
    "en": "Speach",
    "de": "Sprechen",
    "ru": "Speach",
    "pt": "Speach",
    "nl": "Spreek",
    "fr": "Speach",
    "it": "speach",
    "es": "Discurso",
    "pl": "Przemówienie",
    "zh-cn": "话语"
  },
  "Spoken sentence": {
    "en": "Spoken sentence",
    "de": "Gesprochener Satz",
    "ru": "Разговорный приговор",
    "pt": "Frase falada",
    "nl": "Gesproken zin",
    "fr": "Phrase prononcée",
    "it": "Frase parlata",
    "es": "Oración hablada",
    "pl": "Wypowiedziane zdanie",
    "zh-cn": "口语句"
  },
    "Sentence": {
    "en": "Sentence",
    "de": "Satz",
    "ru": "Приговор",
    "pt": "Sentença",
    "nl": "Zin",
    "fr": "Phrase",
    "it": "Frase",
    "es": "Frase",
    "pl": "Zdanie",
    "zh-cn": "句子"
  },
  "Value": {
    "en": "Value",
    "de": "Wert",
    "ru": "Стоимость",
    "pt": "Valor",
    "nl": "Waarde",
    "fr": "Valeur",
    "it": "Valore",
    "es": "Valor",
    "pl": "Wartość",
    "zh-cn": "值"
  },
   "Time": {
    "en": "Time",
    "de": "Zeit",
    "ru": "Время",
    "pt": "Tempo",
    "nl": "Tijd",
    "fr": "Temps",
    "it": "Tempo",
    "es": "Hora",
    "pl": "Czas",
    "zh-cn": "时间"
  },
    "Sensor object": {
    "en": "Sensor object",
    "de": "Sensorobjekt",
    "ru": "Объект датчика",
    "pt": "Objeto sensor",
    "nl": "Sensor object",
    "fr": "Objet capteur",
    "it": "Oggetto sensore",
    "es": "Objeto sensor",
    "pl": "Obiekt czujnika",
    "zh-cn": "传感器对象"
  },
    "Temperature object": {
    "en": "Temperature object",
    "de": "Temperaturobjekt",
    "ru": "Объект температуры",
    "pt": "Objeto de temperatura",
    "nl": "Temperatuurobject",
    "fr": "Objet de température",
    "it": "Oggetto temperatura",
    "es": "Objeto de temperatura",
    "pl": "Temperatura obiektu",
    "zh-cn": "温度物体"
  },
    "Temperature value": {
    "en": "Temperature value",
    "de": "Temperaturwert",
    "ru": "Значение температуры",
    "pt": "Valor de temperatura",
    "nl": "Temperatuurwaarde",
    "fr": "Valeur de température",
    "it": "Valore della temperatura",
    "es": "Valor de temperatura",
    "pl": "Wartość temperatury",
    "zh-cn": "温度值"
  },
    "Entrance": {
    "en": "Entrance",
    "de": "Eingang",
    "ru": "Вход",
    "pt": "Entrada",
    "nl": "Ingang",
    "fr": "entrée",
    "it": "Entrata",
    "es": "Entrada",
    "pl": "Wejście",
    "zh-cn": "入口"
  },
    "Illumination object": {
    "en": "Illumination object",
    "de": "Beleuchtungsobjekt",
    "ru": "Объект освещения",
    "pt": "Objeto de iluminação",
    "nl": "Verlichtingsobject",
    "fr": "Objet d'éclairage",
    "it": "Oggetto di illuminazione",
    "es": "Objeto de iluminación",
    "pl": "Obiekt oświetleniowy",
    "zh-cn": "照明对象"
  },
    "Illumination": {
    "en": "Illumination",
    "de": "Beleuchtung",
    "ru": "освещения",
    "pt": "iluminação",
    "nl": "Verlichting",
    "fr": "Éclairage",
    "it": "Illuminazione",
    "es": "Iluminación",
    "pl": "Oświetleniowy",
    "zh-cn": "照明"
  },
   "Motion object": {
    "en": "Motion object",
    "de": "Bewegungsobjekt",
    "ru": "Объект движения",
    "pt": "Objeto de movimento",
    "nl": "Bewegingsobject",
    "fr": "Objet de mouvement",
    "it": "Oggetto di movimento",
    "es": "Objeto de movimiento",
    "pl": "Obiekt ruchu",
    "zh-cn": "运动物体"
  },
	"Motion value": {
    "en": "Motion value",
    "de": "Bewegungswert",
    "ru": "Значение движения",
    "pt": "Valor de movimento",
    "nl": "Bewegingswaarde",
    "fr": "Valeur de mouvement",
    "it": "Valore di movimento",
    "es": "Valor de movimiento",
    "pl": "Wartość ruchu",
    "zh-cn": "运动值"
  },
  "Illumination value": {
    "en": "Illumination value",
    "de": "Beleuchtungswert",
    "ru": "Значение освещенности",
    "pt": "Valor de iluminação",
    "nl": "Verlichtingswaarde",
    "fr": "Valeur d'éclairage",
    "it": "Valore di illuminazione",
    "es": "Valor de iluminación",
    "pl": "Wartość oświetlenia",
    "zh-cn": "照度值"
  },
  "Seconds of the switch-on time": {
    "en": "Seconds of the switch-on time",
    "de": "Sekunden der Einschaltzeit",
    "ru": "Секунды времени включения",
    "pt": "Segundos da hora de ligar",
    "nl": "Seconden van de inschakeltijd",
    "fr": "Secondes de l'heure de mise en marche",
    "it": "Secondi del tempo di accensione",
    "es": "Segundos del tiempo de encendido",
    "pl": "Sekundy czasu włączenia",
    "zh-cn": "开机时间（秒）"
  },
   "Trigger time": {
    "en": "Trigger time",
    "de": "Auslösezeit",
    "ru": "Время срабатывания",
    "pt": "Tempo de disparo",
    "nl": "Trigger tijd",
    "fr": "Temps de déclenchement",
    "it": "Tempo di attivazione",
    "es": "Tiempo de activación",
    "pl": "Czas wyzwalania",
    "zh-cn": "触发时间"
  },
    "Activate schedule": {
    "en": "Activate schedule",
    "de": "Zeitplan aktivieren",
    "ru": "Активировать расписание",
    "pt": "Ativar programação",
    "nl": "Activeer schema",
    "fr": "Activer le calendrier",
    "it": "Attiva la pianificazione",
    "es": "Activar horario",
    "pl": "Aktywuj harmonogram",
    "zh-cn": "激活时间表"
  },
    "Start": {
    "en": "Start",
    "de": "Anfang",
    "ru": "Начало",
    "pt": "Começar",
    "nl": "Begin",
    "fr": "Début",
    "it": "Inizio",
    "es": "comienzo",
    "pl": "Początek",
    "zh-cn": "开始"
  },
    "End": {
    "en": "End",
    "de": "Ende",
    "ru": "Конец",
    "pt": "Fim",
    "nl": "Einde",
    "fr": "Fin",
    "it": "Fine",
    "es": "Final",
    "pl": "Koniec",
    "zh-cn": "结束"
  },
    "Activate Device": {
    "en": "Activate Device",
    "de": "Gerät aktivieren",
    "ru": "Активировать устройство",
    "pt": "Ativar dispositivo",
    "nl": "Activeer apparaat",
    "fr": "Activer l'appareil",
    "it": "Attiva dispositivo",
    "es": "Activar dispositivo",
    "pl": "Aktywuj urządzenie",
    "zh-cn": "激活设备"
  },
    "Add Device": {
    "en": "Add Device",
    "de": "Gerät hinzufügen",
    "ru": "Добавить устройство",
    "pt": "Adicionar Dispositivo",
    "nl": "Voeg toestel toe",
    "fr": "Ajouter un appareil",
    "it": "Aggiungi dispositivo",
    "es": "Añadir dispositivo",
    "pl": "Dodaj urządzenie",
    "zh-cn": "添加设备"
  },
    "Monday": {
    "en": "Monday",
    "de": "Montag",
    "ru": "понедельник",
    "pt": "Segunda-feira",
    "nl": "maandag",
    "fr": "Lundi",
    "it": "Lunedi",
    "es": "lunes",
    "pl": "poniedziałek",
    "zh-cn": "星期一"
  },
    "Tuesday": {
    "en": "Tuesday",
    "de": "Dienstag",
    "ru": "вторник",
    "pt": "terça",
    "nl": "dinsdag",
    "fr": "Mardi",
    "it": "martedì",
    "es": "martes",
    "pl": "wtorek",
    "zh-cn": "星期二"
  },
    "Wednesday": {
    "en": "Wednesday",
    "de": "Mittwoch",
    "ru": "среда",
    "pt": "Quarta feira",
    "nl": "woensdag",
    "fr": "Mercredi",
    "it": "mercoledì",
    "es": "miércoles",
    "pl": "środa",
    "zh-cn": "星期三"
  },
   "Thursday": {
    "en": "Thursday",
    "de": "Donnerstag",
    "ru": "Четверг",
    "pt": "Quinta feira",
    "nl": "donderdag",
    "fr": "Jeudi",
    "it": "giovedi",
    "es": "jueves",
    "pl": "czwartek",
    "zh-cn": "星期四"
  },
  "Friday": {
    "en": "Friday",
    "de": "Freitag",
    "ru": "пятница",
    "pt": "Sexta-feira",
    "nl": "vrijdag",
    "fr": "Vendredi",
    "it": "Venerdì",
    "es": "viernes",
    "pl": "piątek",
    "zh-cn": "星期五"
  },
  "Saturday": {
    "en": "Saturday",
    "de": "Samstag",
    "ru": "суббота",
    "pt": "sábado",
    "nl": "zaterdag",
    "fr": "samedi",
    "it": "Sabato",
    "es": "sábado",
    "pl": "sobota",
    "zh-cn": "星期六"
  },
  "Sunday": {
    "en": "Sunday",
    "de": "Sonntag",
    "ru": "Воскресенье",
    "pt": "domingo",
    "nl": "zondag",
    "fr": "dimanche",
    "it": "Domenica",
    "es": "domingo",
    "pl": "niedziela",
    "zh-cn": "星期日"
  },

  "sunrise": {
    "en": "sunrise",
    "de": "Sonnenaufgang",
    "ru": "Восход",
    "pt": "nascer do sol",
    "nl": "zonsopkomst",
    "fr": "lever du soleil",
    "it": "Alba",
    "es": "amanecer",
    "pl": "wschód słońca",
    "zh-cn": "日出"
  },
  "sunrise (top edge of the sun appears on the horizon)": {
    "en": "sunrise (top edge of the sun appears on the horizon)",
    "de": "Sonnenaufgang (Oberkante der Sonne erscheint am Horizont)",
    "ru": "восход солнца (на горизонте появляется верхний край солнца)",
    "pt": "nascer do sol (a borda superior do sol aparece no horizonte)",
    "nl": "zonsopgang (bovenrand van de zon verschijnt aan de horizon)",
    "fr": "lever du soleil (le bord supérieur du soleil apparaît à l'horizon)",
    "it": "alba (il bordo superiore del sole appare all'orizzonte)",
    "es": "amanecer (el borde superior del sol aparece en el horizonte)",
    "pl": "wschód słońca (na horyzoncie pojawia się górna krawędź słońca)",
    "zh-cn": "日出（太阳的顶部出现在地平线上）"
  },
  "sunriseEnd": {
    "en": "sunriseEnd",
    "de": "SonnenaufgangEnde",
    "ru": "Восход Конец",
    "pt": "sunriseEnd",
    "nl": "zonsopgang",
    "fr": "lever du soleil",
    "it": "sunriseEnd",
    "es": "amanecerEnd",
    "pl": "wschód słońca",
    "zh-cn": "SunriseEnd"
  },
  "sunrise ends (bottom edge of the sun touches the horizon)": {
    "en": "sunrise ends (bottom edge of the sun touches the horizon)",
    "de": "Sonnenaufgang endet (unterer Rand der Sonne berührt den Horizont)",
    "ru": "заканчивается восход солнца (нижний край солнца касается горизонта)",
    "pt": "o nascer do sol termina (a borda inferior do sol toca o horizonte)",
    "nl": "zonsopgang eindigt (onderkant van de zon raakt de horizon)",
    "fr": "le lever du soleil se termine (le bord inférieur du soleil touche l'horizon)",
    "it": "l'alba finisce (il bordo inferiore del sole tocca l'orizzonte)",
    "es": "el amanecer termina (el borde inferior del sol toca el horizonte)",
    "pl": "kończy się wschód słońca (dolna krawędź słońca dotyka horyzontu)",
    "zh-cn": "日出结束（太阳的底部触及地平线）"
  },
  "goldenHourEnd": {
    "en": "goldenHourEnd",
    "de": "goldenHourEnd",
    "ru": "goldenHourEnd",
    "pt": "goldenHourEnd",
    "nl": "goldenHourEnd",
    "fr": "goldenHourEnd",
    "it": "goldenHourEnd",
    "es": "goldenHourEnd",
    "pl": "goldenHourEnd",
    "zh-cn": "goldenHourEnd"
  },
  "morning golden hour (soft light, best time for photography) ends": {
    "en": "morning golden hour (soft light, best time for photography) ends",
    "de": "Die goldene Morgenstunde (weiches Licht, beste Zeit zum Fotografieren) endet",
    "ru": "заканчивается утренний золотой час (мягкий свет, лучшее время для фотосъемки)",
    "pt": "hora de ouro da manhã (luz suave, melhor hora para a fotografia) termina",
    "nl": "het gouden uur van de ochtend (zacht licht, beste tijd voor fotografie) eindigt",
    "fr": "l'heure dorée du matin (lumière douce, meilleur moment pour la photographie) se termine",
    "it": "l'ora d'oro del mattino (luce soffusa, periodo migliore per la fotografia) finisce",
    "es": "finaliza la hora dorada de la mañana (luz suave, mejor momento para la fotografía)",
    "pl": "kończy się poranna złota godzina (miękkie światło, najlepszy czas na fotografowanie)",
    "zh-cn": "金色的早晨（柔和的光线，最佳摄影时间）结束"
  },
  "solarNoon ": {
    "en": "solarNoon ",
    "de": "SolarNoon",
    "ru": "солнечный",
    "pt": "solarNoon",
    "nl": "solarNoon",
    "fr": "solaire",
    "it": "solarNoon",
    "es": "mediodía solar",
    "pl": "solarNoon",
    "zh-cn": "星期日"
  },
  "solar noon (sun is in the highest position)": {
    "en": "solar noon (sun is in the highest position)",
    "de": "Sonnenmittag (Sonne steht am höchsten)",
    "ru": "солнечный полдень (солнце находится в самом высоком положении)",
    "pt": "meio-dia solar (o sol está na posição mais alta)",
    "nl": "zonne-middag (zon staat in de hoogste stand)",
    "fr": "midi solaire (le soleil est dans la position la plus élevée)",
    "it": "mezzogiorno solare (il sole è nella posizione più alta)",
    "es": "mediodía solar (el sol está en la posición más alta)",
    "pl": "południe słoneczne (słońce jest w najwyższej pozycji)",
    "zh-cn": "星期日正午（太阳在最高位置）"
  },
  "goldenHour": {
    "en": "goldenHour",
    "de": "goldene Stunde",
    "ru": "золотой час",
    "pt": "Hora dourada",
    "nl": "gouden uur",
    "fr": "goldenHour",
    "it": "goldenHour",
    "es": "hora dorada",
    "pl": "złota godzina",
    "zh-cn": "黄金小时"
  },
  "evening golden hour starts": {
    "en": "evening golden hour starts",
    "de": "Die goldene Abendstunde beginnt",
    "ru": "начинается вечерний золотой час",
    "pt": "hora de ouro da noite começa",
    "nl": "avond gouden uur begint",
    "fr": "l'heure d'or du soir commence",
    "it": "inizia l'ora d'oro della sera",
    "es": "comienza la hora dorada de la tarde",
    "pl": "zaczyna się złota godzina wieczorem",
    "zh-cn": "黄金时间傍晚开始"
  },
  "sunsetStart": {
    "en": "sunsetStart",
    "de": "sunsetStart",
    "ru": "закат",
    "pt": "sunsetStart",
    "nl": "zonsondergangStart",
    "fr": "coucher de soleil",
    "it": "tramontoStart",
    "es": "SunsetStart",
    "pl": "sunsetStart",
    "zh-cn": "sunsetStart"
  },
  "sunset starts (bottom edge of the sun touches the horizon)": {
    "en": "sunset starts (bottom edge of the sun touches the horizon)",
    "de": "Sonnenuntergang beginnt (unterer Rand der Sonne berührt den Horizont)",
    "ru": "начинается закат (нижний край солнца касается горизонта)",
    "pt": "o pôr do sol começa (a borda inferior do sol toca o horizonte)",
    "nl": "zonsondergang begint (onderkant van de zon raakt de horizon)",
    "fr": "le coucher du soleil commence (le bord inférieur du soleil touche l'horizon)",
    "it": "inizia il tramonto (il bordo inferiore del sole tocca l'orizzonte)",
    "es": "comienza el atardecer (el borde inferior del sol toca el horizonte)",
    "pl": "początek zachodu słońca (dolna krawędź słońca dotyka horyzontu)",
    "zh-cn": "日落开始（太阳底边触及地平线）"
  },
  "sunset": {
    "en": "sunset",
    "de": "Sonnenuntergang",
    "ru": "заход солнца",
    "pt": "pôr do sol",
    "nl": "zonsondergang",
    "fr": "le coucher du soleil",
    "it": "tramonto",
    "es": "puesta de sol",
    "pl": "zachód słońca",
    "zh-cn": "日落"
  },
  "sunset (sun disappears below the horizon, evening civil twilight starts)": {
    "en": "sunset (sun disappears below the horizon, evening civil twilight starts)",
    "de": "Sonnenuntergang (Sonne verschwindet unter dem Horizont, abendliche zivile Dämmerung beginnt)",
    "ru": "закат (солнце скрывается за горизонтом, начинаются вечерние гражданские сумерки)",
    "pt": "pôr do sol (o sol desaparece abaixo do horizonte, o crepúsculo civil da noite começa)",
    "nl": "zonsondergang (zon verdwijnt onder de horizon, burgerlijke avondschemering begint)",
    "fr": "coucher de soleil (le soleil disparaît sous l'horizon, le crépuscule civil du soir commence)",
    "it": "tramonto (il sole scompare sotto l'orizzonte, inizia il crepuscolo civile serale)",
    "es": "puesta de sol (el sol desaparece bajo el horizonte, comienza el crepúsculo civil vespertino)",
    "pl": "zachód słońca (słońce znika za horyzontem, zaczyna się zmierzch cywilny)",
    "zh-cn": "日落（太阳消失在地平线以下，傍晚的民航开始）"
  },
  "dusk": {
    "en": "dusk",
    "de": "Dämmerung",
    "ru": "сумерки",
    "pt": "crepúsculo",
    "nl": "schemer",
    "fr": "crépuscule",
    "it": "crepuscolo",
    "es": "oscuridad",
    "pl": "zmierzch",
    "zh-cn": "黄昏"
  },
  "dusk (evening nautical twilight starts)": {
    "en": "dusk (evening nautical twilight starts)",
    "de": "Abenddämmerung (abendliche nautische Dämmerung beginnt)",
    "ru": "сумерки (начинаются вечерние морские сумерки)",
    "pt": "crepúsculo (começa o crepúsculo náutico da noite)",
    "nl": "schemering (avond nautische schemering begint)",
    "fr": "crépuscule (le crépuscule nautique du soir commence)",
    "it": "crepuscolo (inizia il crepuscolo nautico serale)",
    "es": "anochecer (comienza el crepúsculo náutico vespertino)",
    "pl": "zmierzch (wieczorny zmierzch żeglarski)",
    "zh-cn": "黄昏（暮色航海开始）"
  },
  "nauticalDusk": {
    "en": "nauticalDusk",
    "de": "nauticalDusk",
    "ru": "морскойСумерки",
    "pt": "náutico crepúsculo",
    "nl": "nauticalDusk",
    "fr": "nautiqueCrépuscule",
    "it": "nautico Crepuscolo",
    "es": "náutico",
    "pl": "nauticalDusk",
    "zh-cn": "航海黄昏"
  },
  "nautical dusk (evening astronomical twilight starts)": {
    "en": "nautical dusk (evening astronomical twilight starts)",
    "de": "nautische Dämmerung (abends beginnt die astronomische Dämmerung)",
    "ru": "морские сумерки (начинаются вечерние астрономические сумерки)",
    "pt": "crepúsculo náutico (começa o crepúsculo astronômico da noite)",
    "nl": "nautische schemering (avond astronomische schemering begint)",
    "fr": "crépuscule nautique (le crépuscule astronomique du soir commence)",
    "it": "crepuscolo nautico (inizia il crepuscolo astronomico serale)",
    "es": "anochecer náutico (comienza el crepúsculo astronómico vespertino)",
    "pl": "morski zmierzch (początek zmierzchu astronomicznego)",
    "zh-cn": "航海黄昏（晚上天文暮光开始）"
  },
  "night": {
    "en": "night",
    "de": "Nacht",
    "ru": "ночь",
    "pt": "noite",
    "nl": "nacht",
    "fr": "nuit",
    "it": "notte",
    "es": "noche",
    "pl": "noc",
    "zh-cn": "晚"
  },
  "night starts (dark enough for astronomical observations)": {
    "en": "night starts (dark enough for astronomical observations)",
    "de": "Die Nacht beginnt (dunkel genug für astronomische Beobachtungen)",
    "ru": "начинается ночь (достаточно темно для астрономических наблюдений)",
    "pt": "a noite começa (escuro o suficiente para observações astronômicas)",
    "nl": "nacht begint (donker genoeg voor astronomische waarnemingen)",
    "fr": "la nuit commence (assez sombre pour les observations astronomiques)",
    "it": "inizia la notte (abbastanza buio per le osservazioni astronomiche)",
    "es": "comienza la noche (lo suficientemente oscuro para observaciones astronómicas)",
    "pl": "początek nocy (dostatecznie ciemno do obserwacji astronomicznych)",
    "zh-cn": "夜幕降临（足够黑暗以进行天文观测）"
  },
  "nadir": {
    "en": "nadir",
    "de": "Nadir",
    "ru": "надир",
    "pt": "nadir",
    "nl": "nadir",
    "fr": "nadir",
    "it": "nadir",
    "es": "nadir",
    "pl": "nadir",
    "zh-cn": "天底"
  },
  "nadir (darkest moment of the night, sun is in the lowest position)": {
    "en": "nadir (darkest moment of the night, sun is in the lowest position)",
    "de": "Nadir (dunkelster Moment der Nacht, Sonne steht am niedrigsten)",
    "ru": "надир (самый темный момент ночи, солнце находится в самом низком положении)",
    "pt": "nadir (momento mais escuro da noite, o sol está na posição mais baixa)",
    "nl": "nadir (donkerste moment van de nacht, zon staat in de laagste stand)",
    "fr": "nadir (moment le plus sombre de la nuit, le soleil est dans la position la plus basse)",
    "it": "nadir (momento più buio della notte, il sole è nella posizione più bassa)",
    "es": "nadir (momento más oscuro de la noche, el sol está en la posición más baja)",
    "pl": "nadir (najciemniejszy moment nocy, słońce jest w najniższej pozycji)",
    "zh-cn": "天底（夜晚最暗的时刻，太阳处于最低位置）"
  },
  "nightEnd": {
    "en": "nightEnd",
    "de": "Nachtende",
    "ru": "nightEnd",
    "pt": "fim da noite",
    "nl": "nightEnd",
    "fr": "nuitFin",
    "it": "nightEnd",
    "es": "noche",
    "pl": "nightEnd",
    "zh-cn": "nightEnd"
  },
  "night ends (morning astronomical twilight starts)": {
    "en": "night ends (morning astronomical twilight starts)",
    "de": "Die Nacht endet (die astronomische Dämmerung am Morgen beginnt)",
    "ru": "заканчивается ночь (начинаются утренние астрономические сумерки)",
    "pt": "termina a noite (começa o crepúsculo astronômico da manhã)",
    "nl": "nacht eindigt (ochtend astronomische schemering begint)",
    "fr": "la nuit se termine (le crépuscule astronomique du matin commence)",
    "it": "la notte finisce (inizia il crepuscolo astronomico mattutino)",
    "es": "termina la noche (comienza el crepúsculo astronómico de la mañana)",
    "pl": "kończy się noc (zaczyna się poranny zmierzch astronomiczny)",
    "zh-cn": "夜晚结束（早晨天文暮光开始）"
  },
  "nauticalDawn": {
    "en": "nauticalDawn",
    "de": "nauticalDawn",
    "ru": "морской рассвет",
    "pt": "nauticalDawn",
    "nl": "nautischDawn",
    "fr": "nautiqueAube",
    "it": "nauticalDawn",
    "es": "Amanecer náutico",
    "pl": "nauticalDawn",
    "zh-cn": "航海的黎明"
  },
  "nautical dawn (morning nautical twilight starts)": {
    "en": "nautical dawn (morning nautical twilight starts)",
    "de": "nautische Morgendämmerung (morgendliche nautische Dämmerung beginnt)",
    "ru": "морской рассвет (начинаются утренние морские сумерки)",
    "pt": "amanhecer náutico (começa o crepúsculo náutico matinal)",
    "nl": "nautische dageraad (nautische ochtendschemering begint)",
    "fr": "aube nautique (le crépuscule nautique du matin commence)",
    "it": "alba nautica (inizia il crepuscolo nautico mattutino)",
    "es": "amanecer náutico (comienza el crepúsculo náutico matutino)",
    "pl": "żeglarski świt (poranny zmierzch żeglarski)",
    "zh-cn": "航海黎明（早晨航海暮光开始）"
  },
  "dawn": {
    "en": "dawn",
    "de": "Dämmerung",
    "ru": "рассвет",
    "pt": "alvorecer",
    "nl": "dageraad",
    "fr": "Aube",
    "it": "alba",
    "es": "amanecer",
    "pl": "świt",
    "zh-cn": "黎明"
  },
  "dawn (morning nautical twilight ends, morning civil twilight starts)": {
    "en": "dawn (morning nautical twilight ends, morning civil twilight starts)",
    "de": "Morgendämmerung (die nautische Dämmerung am Morgen endet, die zivile Dämmerung am Morgen beginnt)",
    "ru": "рассвет (заканчиваются утренние морские сумерки, начинаются утренние гражданские сумерки)",
    "pt": "amanhecer (termina o crepúsculo náutico matinal, começa o crepúsculo civil matinal)",
    "nl": "dageraad (nautische ochtendschemering eindigt, burgerlijke ochtendschemering begint)",
    "fr": "l'aube (le crépuscule nautique du matin se termine, le crépuscule civil du matin commence)",
    "it": "alba (finisce il crepuscolo nautico mattutino, inizia il crepuscolo civile mattutino)",
    "es": "amanecer (el crepúsculo náutico matutino termina, comienza el crepúsculo civil matutino)",
    "pl": "świt (kończy się poranny zmierzch żeglarski, zaczyna się świt cywilny)",
    "zh-cn": "黎明（上午航海暮色结束，早晨民航暮色开始）"
  }


};